DATA_FOLDER: "/nobackup3/hkhader/datasets/olive"

vision_encoder: "openai/clip-vit-large-patch14-336"

llm_model: "gpt2"

no_compression: False
freeze_vision_encoder: True
freeze_llm: False
save_folder: "/nobackup3/hkhader/datasets/outputs/olive/checkpoints"
model_save_load_name_prefix: "classification_and_detailed_image_captioning" #"detailed_image_captioning" # add it to the default naming


task: "classification_and_detailed_image_captioning"

# Use object level annotations for training/eval image captioning/VQA
use_object_annotations: True
system_prompt: "You are a helpful vision assistant trained to help people analyze images."
device: "cuda:0"

n_decoder_layers: 32
batch_size: 4 #2
learning_rate: 0.00002 #0.00002
early_stopping: False
check_loss_steps: 1000
examples_per_class: 1000000
pretrained_object_encoder_checkpoint: "None"
n_epochs: 1



# model name which will be used to save it or load it. Othwewise it choose default starting at save_folder/default_name
#load_model_path: "./checkpoints/llama_2_finetuned_checkpoints/object_classification/finetuned_llm_clip_336_retrieval_24x24_patches"



#retrieval_set_path: "retrieval/medical_object_classification/retrieval_set_1000000_cropped_clip-vit-large-patch14-336.pkl"
# my generated retrival set
retrieval_set_path: "retrieval/object_classification/retrieval_set_1000000_clip-vit-large-patch14-336.pkl"

use_retrieval: False # Whether or not to retrieve in-context examples
retrieval_k: 5 # Number of retrieved in-context examples
majority_vote_retrieval: False
use_image_features: False # Concatenate ViT Image Features to LLM Input Embeddings (slow!)
crop_image: False


n_patches: 24


load_pretrained_model: False
